### PR TITLE
NEW: Update core icon set - Part 1

### PR DESCRIPTION
**Pull request by un1versal**
This is a initial pull request to replace the core images used in Kvirc.

These changes started as a my own themes for my personal and friends/family Kvirc usage as I found many of the images no longer matched the default set found in Kvirc and were also starting to look dated.

**Attribution:**
Since a bulk of of these images belong to "Farm-Fresh Web Icons" set found at http://www.fatcow.com/free-icons and are licensed under a [CC v3 licence](http://creativecommons.org/licenses/by/3.0/us/) we must add a respective attribution and make note that they are modified and include a link to webpage which is added in 83dcc15

**Changes:**
Many Icons in this Kvirc set have been modified to suit the program functions they intend to illustrate.
Quite considerable portion of these icons were created in the same style and did not exist in the set and are exclusive to Kvirc.

Further changes to Kvirc source files is required, like the **popups** so that the images reflect the correct images. This is a bug in theme handler or even original popups file which was using meaningless files to illustrate the function they are intended for.

The theme handler in Kvirc seems quite buggy so its hard to tell what issues are caused by it and affect the correct icons being shown for each function/popup entry and other areas of program.

Hopefully with some help we can figure this lot up

### CODE REVIEW

**Comment by un1versal** [comment]
Here are a few screenshots splice and cuts to illustrate how it iconset looks in use. Just for a general idea sort of thing

**Comment by wodim** [comment]
I'm not sure how well these blend into KDE, they look very tangoish. I wish we could get some Oxygen (or however it's called now) love...

**Comment by Stanzilla** [comment]
http://www.iconarchive.com/show/oxygen-icons-by-oxygen-icons.org.html like that?

I don't know, to me all those icons look like a Linux distro from the 90s, but I guess Linux stuff still looks that way :p

**Comment by Afforess** [comment]
As a user, I'd comment that the proposed icons look _better_ than the existing default icon set (which looks like it is out of 1998), but are still a bit dated in appearance. It would be nice to get a flat ui icon set.

**Comment by wodim** [comment]
Oxygen is awful too. Is that what KDE uses nowadays? I have not used used KDE in like five years.

**Comment by un1versal** [comment]
Ive never used KDE. I dont particularly care if they blend with the OS be that Windows or Linux (I use Linux mostly and sometimes use Windows).
I care that they all match and make Kvirc look great and that is mission accomplished I think. 

> As a user, I'd comment that the proposed icons look better than the existing default icon set (which looks like it is out of 1998), but are still a bit dated in appearance. It would be nice to get a flat ui icon set.

Thank you for your comments it wasn't an easy task but after a year of using it among ourselves here I decided it was time to share with all Kvirc users. Here is a big plus for using this, any further icons have a commons source and adding any new icons isnt hard now.

I wish it would be as simple to take any icons you guys point out and make a full set that matches, that isnt so simple, so Im not even going to try again. But do feel free to do it yourself.
This set took me near 3 months from start to finish, including making icons from scratch and modifying the existing ones to suit the functions they intend to replace since it wasn't just a copy and paste job.

The current set served Kvirc nicely but it has deep flaws as in they dont even match style among themselves. 

And BTW it was only because Kvirc is now using Git, else making such contribution wouldn't have been possible. So Kudos to whom made this possible.

---

There's still work to be done in the popups the internal kvirc popups is was never right with the old icon set and requires a massive amount of work to make work with this set.
I do however have a fully working user popups file and am trying to figure out how to translate that to the internal one so that the second part of this PR completes the lot.

**Comment by pragmaware** [comment]
I really like the idea of a new icon set.
The old one is... well... old.
I'll take a deeper look at it but i'm in favor of merging this one.

**Comment by SolarAquarion** [comment]
@wodim they use breeze https://github.com/NitruxSA/breeze-icon-theme

**Comment by wodim** [comment]
No smileys in that icon set? That's my only gripe, current smileys don't fit

**Comment by Stanzilla** [comment]
https://github.com/PedroPegueroJr/moonshine-iconpack ?

**Comment by un1versal** [comment]
> No smileys in that icon set? That's my only gripe, current smileys don't fit

Why dont they, they fit perfectly fine with this new set, If this goes in I may consider making new smilies else no.

**Comment by Afforess** [comment]
> This set took me near 3 months from start to finish, including making icons from scratch and modifying >the existing ones to suit the functions they intend to replace since it wasn't just a copy and paste job.

I looked at the pull request, and it did not look simple to me either! I think I didn't really share my opinion very well. I am strongly in favor of using your new icon set as the new default, as it is a big improvement over the existing icons. I think the icons could be even better with more modern themes, but I don't think we should let perfect be the enemy of good. Incremental improvement is always good, and this PR looks good incremental improvement.

I am just a user, not a contributor, but very in favor of merging this icon set in.

**Comment by un1versal** [comment]
> I really like the idea of a new icon set.
> The old one is... well... old.
> I'll take a deeper look at it but i'm in favor of merging this one.

Great :+1: 

The popups need fixing I have a working user popups saved which at least assigns the right icons to the right functions but the internal kvirc one is a great mess, any suggestions?

Also some of the functions throughout program dont seem to assign the correct icon any thoughts? An example (off top of my head) is the help menu the bug report as seen on screenshots uses the **_kcs_bomb**_ instead of **_kcs_bug**_ and a few more doted around arent quite right and have never been right since I use Kvirc.

**Comment by pragmaware** [comment]
The icon kcs_saykvs.png should read "KVS" and not "KCS"

**Comment by pragmaware** [comment]
Changed to use the 'bug' icon in the Bug Report menu entry.
If you see other such things, please report.

**Comment by un1versal** [comment]
> The icon kcs_saykvs.png should read "KVS" and not "KCS"

If you are saying it should be **kvs_saykvs.png** thats OK by me I can send a PR to rename it. However that needs to be fixed also internally in code no? I used the original filenames. where is that referenced in code?

https://github.com/kvirc/KVIrc/blob/16d3c016112fac39e10c20a851bb4f229209840b/src/kvirc/kernel/KviIconManager.cpp#L589 and https://github.com/kvirc/KVIrc/blob/16d3c016112fac39e10c20a851bb4f229209840b/src/kvirc/kernel/KviIconManager.cpp#L372 says kcs_saykvs.png seems right or am I missing something?

> Changed to use the 'bug' icon in the Bug Report menu entry.
> If you see other such things, please report.

Fantastic thank you.

\o/ its merged thank you pragmaware

Now to fix those dammed popups.

**Comment by pragmaware** [comment]
> If you are saying it should be kvs_saykvs.png thats OK by me I can send a PR to rename it. 

Nope: the text in the image should say KVS and not KCS.

**Comment by un1versal** [comment]
AHHH I'll fix that ... thanks and well spoted :D

**Comment by HelLViS69** [comment]
Hi all,
I recall I wrote an addon, named KISS, to switch and replace icon sets.
That addon was written during the 3.2.6 era and now I'm quite sure it needs
some modifications to reflect work made on 4.x.

**Comment by HelLViS69** [comment]
Sorry, previous mail sent not completed by error..
I was saying, what about introduce in KVirc a stuff like KISS to switch
icon sets and let user choose whatever he wants?

HelLViS69

**Comment by Afforess** [comment]
Adding a way to switch icon sets sound great, but it seems important that default icons look good, since that is the first impression any new users will see.

**Comment by un1versal** [comment]
> Sorry, previous mail sent not completed by error.. I was saying, what about introduce in KVirc a stuff like KISS to switch icon sets and let user choose whatever he wants? HelLViS69

I like the idea of passing control over look and feel to the users (on any software, OS or whatever.) and I feel that the internal theme manager needs a great deal of TLC. Perhaps that is and improvement could be an extension of the theme manager then? Im not much of a coder wouldn't even know where to start.

As long as the user community would make full icon sets to go with that idea, then you are cooking with fire. 
As far as I can see the sets in existence are incomplete at best. Usually though hardly anyone steps forward on that front. Just renaming 300 files by hand is a daunting process.

As is currently If I remember correctly I can crash kvirc via theme manager, cant remember what the conditions were but its not pretty. Sure would be nice to have a more robust theme manager built in.
..

**Pull request merged**
