### PR TITLE
Added $dcc.currentSpeed KVS function

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by wodim** [comment]
Does this work?

**Comment by wodim** [comment]
My only problem with this is the name, I think "current" would be more appropriate than "instant", but other than that it looks, well, the way it's meant to look. So if it's good merge it

**Comment by Stanzilla** [comment]
Yeah `instant` is the wrong word here, imo. +1 for `current`

**Comment by ghost** [comment]
Instant is what the internal function is, which is what I mimicked. I don't see an issue with it, but I guess if people want it changed, then ok. I like keeping things consistent. But, 2 votes isn't enough for me.

**Comment by staticfox** [comment]
> Instant is what the internal function is

Users will only ever see the external/api level name of things so if it means breaking consistency against internal naming conventions to be more logical then it is best to do it that way.

**Comment by un1versal** [comment]
+1

Ive no strong opinion on naming if it was a UI option maybe there be room for thought,, If it works, go ;) 

WB btw

**Pull request merged**
