### PR TITLE
numerichandler: Comment out idle stuff for now

### PR DESCRIPTION
**Pull request by staticfox**
GitHub has a new button, I wanna see it :3 (basically the point of this PR/commit)

### CODE REVIEW

**Comment by staticfox** [comment]
Now @un1versal 's fears over merge commits are no more :3

**Comment by un1versal** [comment]
> Now @un1versal 's fears over merge commits are no more :3

Fears? Oh yea, the stuff that night terrors are made of... not.

Its simply unnecessary and ugly.

**Comment by un1versal** [comment]
May need to logout and login, I cant see jack.

**Comment by un1versal** [comment]
Ah I see the button, you need to press the button once then you get the options button...

This however is not a --rebase option, I bet you will still get useless merge commits.

What this squash merge does is, if you made 30 commits into a single PR it squashes them all into one commit and merges it.

**Pull request merged**
