### PR TITLE
Superseeds #1837 rename toolbar applet option and remove unused

### PR DESCRIPTION
**Pull request by un1versal**
@ctrlaltca please have a looksee.

I didnt remove the defines because it seems odd comment them out or remove them due to total count idk what effects that would have. Some other defines have been commented out in past, idk if thats right.

am compiling for a quick runtime test.

### CODE REVIEW

**Comment by un1versal** [comment]
capture

Seems to work just fine...

Ill do internal themes off of that and add changes here and merge if no one has any thing to say about this.

**Comment by un1versal** [comment]
@ctrlaltca should I remove the defines adjust total count and renumber so they match, or will commenting them out be enough?

previously some are just commented out, idk but that seem not right.

**Comment by un1versal** [comment]
this is as ready and as finished as I can get it. please review and kick in

**Comment by un1versal** [comment]
anyone has anything at all to say? if not in by the morning.

**Comment by wodim** [comment]
I have to say that we shouldn't change option names unless it's completely necessary.

**Comment by un1versal** [comment]
They made no sense as they were before according to the current logic and now they at least in the neighborhood of sane, im still having thoughts about the labels names though.

**Pull request merged**
