### PR TITLE
Show spell checker suggestions in a submenu of popup menu.

### PR DESCRIPTION
**Pull request by DarthGandalf**

### CODE REVIEW

**Comment by un1versal** [comment]
+1

Will this make the suggestions immediately available or do you still have to fiddle about?

**Comment by DarthGandalf** [comment]
You still need to select the wanted fix from the list...

**Comment by un1versal** [comment]
Yes sure, what I meant was, will this list be available immediatly or is there fiddling required? 
Currently you need to right click over error, once or twice sometimes even three times before the spellchecker suggestion(s) is available for selection. Otherwise its disabled.

**Comment by DarthGandalf** [comment]
When do you need to click it 3 times? o_O
kvirc 4 3 2 aria - _217
kvirc 4 3 2 aria - _218

**Comment by un1versal** [comment]
Ah I figure it out, if the cursor is not over the word error it doesn't become active.

**Not active** cursor by end of OK
capture1

capture

**Active** cursor at end of word or middle of word
capture2

capture3

So o_O indeed.

**Comment by pragmaware** [comment]
Yes, the suggestions are for the word at cursor.
You can activate the suggestions popup with CTRL+G too.

**Comment by un1versal** [comment]
> Yes, the suggestions are for the word at cursor.
> You can activate the suggestions popup with CTRL+G too.

A more intuitive manner, would be perhaps to be able to activate the suggestions by right clicking over the underlined word.

**Pull request merged**
