### PR TITLE
bump debian build details 4.9.2

### PR DESCRIPTION
**Pull request by un1versal**
@AlexanderP for blessing

### CODE REVIEW

**Comment by staticfox** [comment]
github has "reactions" now? is this facebook?

**Comment by staticfox** [comment]
On the other hand, I think something is up with the PPA, someone mentioned this to me:

```
[8:09:09 PM] <~VASirens> BlindSight: It seems that the KV Git Debian/Ubuntu packages are horribly broken - kvirc conflicts with itself...
[8:42:37 PM] <~VASirens> BlindSight:  <image below>
```

**Comment by AlexanderP** [comment]
@un1versal Ok

**Comment by un1versal** [comment]
@AlexanderP any comment about what @staticfox said? is that happening?

**Comment by AlexanderP** [comment]
this is normal :)
2016-03-12--1457785969_3840x1200_scrot

**Comment by un1versal** [comment]
thx, @staticfox can tell his _someone_ they are headbutting furniture in the dark and that maybe they should turn lights on.

thx Alex

**Comment by AlexanderP** [comment]
@un1versal great job 
+lintian fix

```
diff --git a/dist/debian/control b/dist/debian/control
index c704dfb..abab5c1 100644
@@ -2,7 +2,7 @@ Source: kvirc
 Section: net
 Priority: optional
 Maintainer: Alexander Pozdnyakov <almipo@mail.ru>
-Build-Depends: debhelper (>= 8.9.4),
+Build-Depends: debhelper (>= 9),
  cmake (>= 3.1),
  libperl-dev,
  zlib1g-dev,
@@ -15,12 +15,12 @@ Build-Depends: debhelper (>= 8.9.4),
  libxss-dev,
  python-dev,
  libqtwebkit-dev, libenchant-dev
-Standards-Version: 3.9.6
+Standards-Version: 3.9.7
 Homepage: http://www.kvirc.de/

 Package: kvirc
 Architecture: any
-Pre-Depends: multiarch-support, ${misc:Pre-Depends}
+Pre-Depends: ${misc:Pre-Depends}
 Depends: libkvilib4 (= ${binary:Version}),
  kvirc-modules (= ${binary:Version}),
  kvirc-data (= ${source:Version}),
@@ -42,7 +42,7 @@ Description: KDE-based next generation IRC client with module support
 Package: libkvilib4
 Architecture: any
 Section: libs
-Pre-Depends: multiarch-support, ${misc:Pre-Depends}
+Pre-Depends:  ${misc:Pre-Depends}
 Depends: ${shlibs:Depends}, ${misc:Depends}
 Recommends: kvirc (= ${binary:Version})
 Suggests: kvirc-dbg (= ${binary:Version})
@@ -59,7 +59,7 @@ Description: KVIrc (IRC client) base library
 Package: kvirc-modules
 Architecture: any
 Section: libs
-Pre-Depends: multiarch-support, ${misc:Pre-Depends}
+Pre-Depends: ${misc:Pre-Depends}
 Depends: libkvilib4 (= ${binary:Version}),
  ${shlibs:Depends},
  ${misc:Depends}
diff --git a/dist/debian/kvirc.menu b/dist/debian/kvirc.menu
deleted file mode 100644
@@ -1,7 +0,0 @@
-?package(kvirc):\
- needs="x11"\
- section="Applications/Network/Communication"\
- title="KVIrc"\
- command="/usr/bin/kvirc"\
- hints="KDE,irc,scripting"\
- icon="/usr/share/pixmaps/kvirc32x32.xpm"
```

**Comment by un1versal** [comment]
@AlexanderP 

Ive added you as collaborator, so you are free to update these things as you need from now on..

**Comment by AlexanderP** [comment]
@un1versal Okay. Thanks :)

**Pull request merged**
