### PR TITLE
Activation support for KDE (KF6) notifications

### PR DESCRIPTION
**Pull request by alebastr**
Use xdg-activation tokens when available. This should work with KF6 and `xcb` and `wayland` platform backends on Plasma 6 (Wayland).

Results may vary with other Wayland compositors: there's a really weird interaction with `FlashQueryWindowOnNewMessages` on Sway that should not be permitted by the compositor. GNOME should be fine though.

It's also not worth extracting the lambda as a named function: the whole xdgActivationToken dance is specific to KNotification and not reusable.

### CODE REVIEW

**Comment by ctrlaltca** [comment]
Confirmed working just fine, thank you

**Comment by DarthGandalf** [comment]
Should this also bump the required Qt6 version in CMakeLists.txt?

**Comment by alebastr** [comment]
> Should this also bump the required Qt6 version in CMakeLists.txt?

As @ctrlaltca noted in #2585, KDE Frameworks already does Qt version check for us. It won't be possible to have Qt6, `COMPILE_KDE_SUPPORT` and Qt version below 6.5.
There's also no direct dependency on any of the new Qt APIs.

**Comment by DarthGandalf** [comment]
> It won't be possible to have Qt6, COMPILE_KDE_SUPPORT and Qt version below 6.5.

That's fine. What I mean is a good error message during configure time, instead of a random build-time error.

But it looks like I confused Qt6 version and KF6 version

**Pull request merged**
