### PR TITLE
lithandler: Exec query sounds on query ACTIONs

### PR DESCRIPTION
**Pull request by staticfox**
Right now if someone queries you with an action (i.e. /me) there will be no sound. This fixes it, thoughts?

### CODE REVIEW

**Comment by un1versal** [comment]
OK, just a thought, what about adding this to General Options -> Sounds?

**Comment by staticfox** [comment]
As what? The way CTCP ACTION is treated is no different than a private message really.

**Comment by un1versal** [comment]
No idea, it was my stumble out of bed thought for this.

**Comment by un1versal** [comment]
Alright for me.

**Pull request merged**
