### PR TITLE
Replace maintainer

### PR DESCRIPTION
**Pull request by ghost**
replace my name to current maintainer

### CODE REVIEW

**Comment by wodim** [comment]
That's more of a credits section, I wonder why do you want your name removed... Even if you are not the maintainer anymore.

**Comment by ghost** [comment]
i dont see why people ask questions and cant just go ah this guy wants this removed okie dokie then.

**Comment by ctrlaltca** [comment]
The new maintaner info is confirmed on: https://www.freebsd.org/cgi/ports.cgi?query=kvirc&stype=all , i see no point in debating.

**Comment by un1versal** [comment]
@bsdjunk thank you for this and for being that guy who use to maintain it. be well. ;)

**Pull request merged**
