### PR TITLE
Clang-tidy fixes (modernize-*)

### PR DESCRIPTION
**Pull request by DarthGandalf**
C++14 is to make `modernize-make-unique` produce correct code.

### CODE REVIEW

**Comment by pragmaware** [comment]
Replacing well-formed and easily readable types with "auto" makes the code less readable.
It also confuses simple tools like ctags which are no longer able to determine the types of variables.

**Comment by staticfox** [comment]
It makes sense when you want to auto-away iterators, large class names, etc. but I'm not sure if it's worth it for basic types.

**Comment by IceN9ne** [comment]
C++14 standard also needs to be changed in `cmake/module.rules.txt`.

**Comment by Stanzilla** [comment]
And in `.clang-format`?

**Comment by DarthGandalf** [comment]
Disabled modernize-use-auto.

> cmake/module.rules.txt

Done.

> .clang-format

There's no difference between C++11 and C++14 as far as clang-format is concerned. `Standard` doesn't even have a separate C++14 value.

**Review by IceN9ne — APPROVED** [review]
Looks good without the `auto` changes. All except for a few member initialization lists being split to multiple lines with only 2-3 entries, which i personally could live with, it looks great.

**Comment by DarthGandalf** [comment]
@AlexanderP can you help fixing the debuild travis build for this?

**Review by Stanzilla — APPROVED** [review]

**Comment by Stanzilla** [comment]
Can we just merge this?

**Comment by IceN9ne** [comment]
I'd like to see this successfully build in Travis / AppVeyor first.

**Comment by Stanzilla** [comment]
I restarted the travis build, can't restart AV

**Comment by DarthGandalf** [comment]
The debuild build in travis needs some changes to enable new GCC. But I don't know how to do that.

**Comment by ctrlaltca** [comment]
> I restarted the travis build, can't restart AV

Restarted

**Comment by DarthGandalf** [comment]
Huh, apparently simply waiting for several months helps debuild.

Windows doesn't like it though: https://ci.appveyor.com/project/DarthGandalf/kvirc/builds/20249763/job/haad2i1q52c0bj2q

**Pull request merged**
