### PR TITLE
Various improvements to the French translation

### PR DESCRIPTION
**Pull request by J0celyn**

### CODE REVIEW

**Comment by Stanzilla** [comment]
Please squash your commits when you are done.

**Comment by J0celyn** [comment]
Sorry, I have no idea how to squash commits using Github or Git GUI. I'm still learning how to use Git.
If someone can point me in the right direction...

**Comment by Stanzilla** [comment]
There you go http://stackoverflow.com/questions/14534397/squash-all-my-commits-into-one-for-github-pull-request

**Comment by ctrlaltca** [comment]
I saw you already signed up on Transifex, so i'll close this PR.

**Comment by J0celyn** [comment]
I've just made all these changes in Transifex.

**Pull request closed without merging**
