### PR TITLE
Add EsperNet

### PR DESCRIPTION
**Pull request by lol768**
* Adds [EsperNet](https://esper.net) to the server list.

### CODE REVIEW

**Comment by IceN9ne** [comment]
I'll merge it if you add a non-SSL connection as `0` and move the SSL version to `1`.

**Comment by lol768** [comment]
I'm not encouraging users to use insecure transport, and you shouldn't do the same :/

It's no different to moving towards deprecating HTTP and pushing HTTPS as the preferred way to access web applications.  There are [mature proposals](https://ircv3.net/specs/extensions/sts.html) that implement a HSTS parallel on top of IRC for this very reason.

if you're not willing to budge on this, please do close the PR.

**Comment by IceN9ne** [comment]
The use of SSL when there are no verification mechanisms in place is only a false sense of security.  This false sense of security is more detrimental than knowingly using non-SSL as at least then you'll consider your usage as opposed to potentially leaking sensitive information.

**Comment by lol768** [comment]
>The use of SSL when there are no verification mechanisms in place is only a false sense of security

We don't use self-signed certificates, they are issued by an actual CA after verification of domain ownership. Users being dumb and disabling verification mechanisms doesn't sound like an issue with the underlying transport to me.

KVIrc does support verifying the chain of trust of the presented server certificates, right?

**Comment by IceN9ne** [comment]
I never said it was an issue with the underlying transport. I was eluding to an issue with the current implementation. Also, not everything requires SSL. The world is about choices, just like the choice to use a vhost, +x, or nothing.

**Comment by IceN9ne** [comment]
This philosophical debate will take us nowhere.

**Comment by lol768** [comment]
>I was eluding to an issue with the current implementation

I wouldn't like to speculate without being familiar with the codebase, but KVIrc 4.9.3 was quite happy to connect to a server with an expired cert as well as a self-signed generated cert with the completely wrong commonName when I tested. I guess now I see what you meant.
<details>






</details>

If this is indeed the case, sounds like a pretty serious issue unrelated to this PR that should be fixed as a priority.

Edit: I guess https://github.com/kvirc/KVIrc/issues/1274 is related.

>Also, not everything requires SSL. The world is about choices, just like the choice to use a vhost, +x, or nothing.

Users can still specify their own host/port/SSL combination to manually connect to, no? There is choice there for users, who understand the risk, to make the decision to connect in an insecure manner if they wish.

But when we have services that receive account credentials (which are probably reused by most users) and potentially sensitive conversations in private channels, do you not think it's responsible to do things securely by default?

-----

In any case, thank you for merging the request.

**Pull request merged**
