### PR TITLE
Add Encryption/Decryption for CTCP ACTION

### PR DESCRIPTION
**Pull request by IceN9ne**
- Adds encryption and decryption support for Query and Channel CTCP ACTION messages
- Adds 'Was encrypted' parameter to `OnAction` events
- Changes `/ctcp ACTION` commands to use Query/Channel `ownAction`

Please test this.

NOTE: If you're using a theme, you may need to adjust for the new KVI_OUT_ACTIONCRYPTED.

### CODE REVIEW

**Comment by un1versal** [comment]
> TODO: Add a new icon for KVI_OUT_ACTIONCRYPTED, but I'll need a icon person to do it. Someone interested?

Ill do a ctcp icon with the same crypto bullet the other cryto icons use, Ill add that as a pr to your branch.

**Comment by IceN9ne** [comment]
@un1versal Could you do one for 'Topic` as well?  I'm thinking about doing that next.

Edit:  I was thinking these icons:

> kcs_action.png
> kcs_topic.png

**Comment by un1versal** [comment]
> kcs_action.png
> kcs_topic.png

already exist

https://github.com/kvirc/KVIrc/blob/master/data/pics/coresmall/kcs_action.png
https://github.com/kvirc/KVIrc/blob/master/data/pics/coresmall/kcs_topic.png

You want them with a crypto symbol as well?

**Comment by IceN9ne** [comment]
Yea, that's what I meant. Crypto symbol versions of those.  Thanks.

**Comment by un1versal** [comment]
what the heck? how am I making commits direct on your fork

**Comment by un1versal** [comment]
there the pr to your fork/branch is done with icons. should get you started.

**Pull request merged**
