### PR TITLE
Todo list and release version bump for KVIrc 5.0

### PR DESCRIPTION
**Pull request by un1versal**
### Dont merge this now. Merge only just before release time.

After a brief discussion with Pragma, it was mentioned 5.0.0 as a possibility, so here it is.
Its not set in stone yet, so have at it.

Todo list: (feel free to edit and update at will) in some order of events. (listing my thoughts on process)
- [ ] Bug fixes that should be done before release (please discuss with @blindsighttf2 his plans)
- [ ] Numerics refactor (blindsighttf2)
- [ ] Strings review done (work in progress - me)
- [ ] Transifex? (need someone with credentials to handle the strings push to and from)
- [ ] Other minutiae
- [ ] Merge this PR
- [ ] Create a Aria 5.0 branch from master and remove dev from windows installer?
- [ ] Tag 5.0.0 release from the 5.x branch
- [ ] Bump master to 5.1.0 maybe and update release codename to Quasar

### CODE REVIEW

**Comment by staticfox** [comment]
It's exciting yes, but maybe we should hold off on a PR considering those files are still subject to change (e.g. #1685)

**Comment by DarthGandalf** [comment]
@blindsighttf2 +1

Also 5.0.0 looks like a release.
Before the release some recently introduced regressions need to be fixed (e.g. #1685, #1672)

**Comment by un1versal** [comment]
@DarthGandalf and others, if you find any bug reports that should be fixed before, would you mind attaching the **_5.x.x release milestone**_ to them, please? Ive done the ones you mentioned now :smile:

**Comment by un1versal** [comment]
Updated todo list some event order more or less. please update or add to it or remove steps even reorder them to reflect a better process?.

**Comment by staticfox** [comment]
IMO It'd make _way_ more sense if you put this list in to the 5.x.x - Release milestone.. that way we can see it easier down the road instead of kludging through tons of PRs.

**Comment by un1versal** [comment]
There's a a few problems with that suggestion. I dont see tons of PR's anyway, even if there was you have a 5.0 aria label as well.

1) the todo list is not directly changeable in the milestone description .i.e. you cannot check boxes as you complete something some task in list you need to edit the milestone and check a box and save.

2) you dont really see the milestone description unless you are specifically editing it and you need to click a more button in order to expand and be able to see the description.

Ive added the list to milestone it anyway and its not practical IMO. have a look below.

Default milestone view (useless)
capture

Press more and still cant check any boxes. (yet another button to press to check a box. and then save)
capture1

**Comment by pragmaware** [comment]
Hm... maybe it's better to wait for changing the version number in the sources. If I remember correctly the version policy, 5.0.0 should be used only in a stable-and-released tree. We'll bump it up shortly before releasing.

**Comment by un1versal** [comment]
This PR is precisely for that purpose or did I miss something?

**Comment by staticfox** [comment]
Still, besides a checklist, why we need to make a PR months in advance for super simple things (and in this case, things that really should be done by the maintainer) is beyond me.

**Comment by ctrlaltca** [comment]
> Still, besides a checklist, why we need to make a PR months in advance for super simple things (and in this case, things that really should be done by the maintainer) is beyond me.

:+1:

**Comment by un1versal** [comment]
> Still, besides a checklist, why we need to make a PR months in advance for super simple things (and in this case, things that really should be done by the maintainer) is beyond me.

FYI I done it so anyone looking knows there is something planned, since its been 50 years since last release.

Anyway, I thought it be a nice thought but obviously not. Like you say, let the maintainer do it whoever that is.

**Pull request closed without merging**
