### PR TITLE
Change: Use new Info icon for the about Kvirc menu entry

### PR DESCRIPTION
**Pull request by un1versal**
~~kcs_mdihelp~~
#### Edit

Use Info icon for the menu Kvirc about entry instead -> kcs_info

I cleanup  alignment in the whitespaces in comments for `KviIconManager.cpp` and added a new icon type `Info` which for now is used specifically for this function.

### CODE REVIEW

**Comment by pragmaware** [comment]
Hmmm.... why use "help" in the "about kvirc" entry?

**Comment by un1versal** [comment]
Many softwares out there that uses icons for about menu entries such as this uses the ? or (i) perhaps it would be better to use (i) for information instead?

#### Edit:

we dont have a regular information icon.... mmmm

**Comment by un1versal** [comment]
Ok pragma have a look at this change and confirm its correct, Im not experienced in c++ but seems about right the addition on the **new** info icon.

No longer using mdihelp icon now its a specific new Info icon (updated main post)

Hope this is more suitable now.

**Comment by un1versal** [comment]
Thanks pragma, I take it the c++ changes were correct then...

**Comment by pragmaware** [comment]
Yep :)

**Pull request merged**
