### PR TITLE
2015 - Update internal infernal themes - they're hot off the press

### PR DESCRIPTION
**Pull request by un1versal**
This updates internal themes to 4.3.2.
- Use the default core icons
- Color schemes have been slightly updated to improve readability
- Tweaked message colors
- Added theme icons
- Tweaked Aria's background text.
- Disabled smart nickname colors until https://github.com/kvirc/KVIrc/issues/1563 has some solution.
  This feature makes readability an issue and one shouldn't have to struggle. Usability takes priority over fancy features that dont behave well :smile: 

capture

md

aria

Could always improve in future a tweak here and there.

### CODE REVIEW

**Comment by swarfega** [comment]
Looking good.

**Comment by pragmaware** [comment]
Smart nickname colors should be on in the fancy theme.... it's fancy :)
#1563 is opinion based. Disabling the background introduces a problem that can't easily be solved.

**Comment by un1versal** [comment]
I can enable it back no big deal, but (if Im honest) #1563 is a usability problem and the main reason why I started this themes icons thing in first place :) because built in themes were extremely hard on the more visually impaired users, like me, and before I could actually use KVIrc as replacement IRC client I had to make own theme

**Comment by pragmaware** [comment]
Well... making the themes more readable is a good thing.
Though I think that the fancy theme should show all the available "fanciness" :D
One can still disable the smart nickname coloring after installing the fancy theme...

**Comment by un1versal** [comment]
Do you think all users are aware they can disable it or even want to be that involved in IRC configuration outside the requirements to connect?

Ill enabled it no worries.

also while we are here...

Can we add more themes in by default so that they can be selected in theme manager? its like less that 50KB each. Not at setup time, thats for these here I was thinking simple light dark and black with softer color schemes.

**Comment by un1versal** [comment]
This built OK (until I resync) and Ive enabled smart colors in Aria all the trims for fancy stuffs.

Ill merge now so that these things can be tested and we can take it from there if anything further needs adjusting.

**Comment by pragmaware** [comment]
:+1:

**Comment by un1versal** [comment]
Small problem, in Linux the 1.0.0 themes arent removed and you cant unistall KVIrc since its compiled.

**Comment by pragmaware** [comment]
You're right. This is a well known limitation of source based installs.
It would be also a bad practice to try to remove the files programmatically as they may have been changed by the user (beside the fact that kvirc is usually installed in a system-wide directory but started with non-root privileges).

**Pull request merged**
