### PR TITLE
run CodeMaid

### PR DESCRIPTION
**Pull request by Stanzilla**
Ran CodeMaid (http://www.codemaid.net/)

Open for discussion on options/style

### CODE REVIEW

**Comment by wodim** [comment]
I vote no because the current style is not bad enough to justify destroying the entire history.

**Comment by Stanzilla** [comment]
CodeMaid can be adapted to the current style and then can apply it consistently. I just need to find the correct options

**Comment by DarthGandalf** [comment]
What's wrong with clang-format?
P.S. When I've run clang-format on the whole KVIrc, I also tuned its settings to match existing style, more or less.

**Comment by Stanzilla** [comment]
Nothing, I'm just playing around

**Pull request closed without merging**
