### PR TITLE
DO NOT MERGE: Smart nick colours with no background.

### PR DESCRIPTION
**Pull request by wodim**
Just so AppVeyor kicks in

### CODE REVIEW

**Comment by un1versal** [comment]
this would fix https://github.com/kvirc/KVIrc/issues/353  which is an amalgamation of all reports that would be sovled by this.

thx for adding this

**Comment by wodim** [comment]
Well, it's still just a test to see how it looks like, it still needs to be actually implemented.

**Comment by un1versal** [comment]
sure

FYI add wip label is same as do not merge. Work in Progress = not ready to merge

**Comment by wodim** [comment]
It looks good. I'll finish this some day.

**Comment by un1versal** [comment]
> It looks good. I'll finish this some day.

Excellent is that the 31st of February?

**Comment by wodim** [comment]
No, the next time you get laid.

**Comment by staticfox** [comment]
Rekt ☑

**Comment by un1versal** [comment]
> No, the next time you get laid.

There's a popular saying that goes: "Familiarity breeds contempt." and that applies to you.

**Comment by wodim** [comment]
Oh come on, we aren't that close yet 😘

**Pull request closed without merging**
