### PR TITLE
fix recognizing https:// URL in CTCP AVATAR replies

### PR DESCRIPTION
**Pull request by un1versal**
thx @Andrio for pointing it out.

Someone that understands this should review and merge.

Personally I cant see a difference and https://github.com/kvirc/KVIrc/issues/1835 is still buggy even with this.

### CODE REVIEW

**Comment by wodim** [comment]
Change `KviQString::equalCIN("https://",szRemoteFile,7)` for `KviQString::equalCIN("https://",szRemoteFile,8)`

**Comment by un1versal** [comment]
> Change KviQString::equalCIN("https://",szRemoteFile,7) for KviQString::equalCIN("https://",szRemoteFile,8)

if thats true then https://github.com/kvirc/KVIrc/blob/master/src/modules/avatar/libkviavatar.cpp#L243 also needs to be 8
added in https://github.com/kvirc/KVIrc/commit/1245875326a5be9600696e417095da21f49d40ce please confirm.

**Comment by wodim** [comment]
ya

**Comment by un1versal** [comment]
well this is it... if you want it merge it...

Personally I cant see a difference and #1835 is still same bug even with this.

**Pull request merged**
