### PR TITLE
W.I.P.: combine OS specific build stuffs into a single directory

### PR DESCRIPTION
**Pull request by un1versal**
Our OS specific directories are somewhat all over the place and I think we should put them all under one roof (**dist** directory) and whenever a new distro or OS support is added things are consistent and can be found in somewhat more logical place...

This is the initial WIP for this proposal.
## Collaborating with this PR

If you have some changes that are faster done than explained, to help this happen you can either add fixes directly to my branch Repo Man as a PR, or just make some detailed feedback.
- Add me as remote `git remote add un1versal https://github.com/un1versal/KVIrc`
- fetch my remote `git fetch un1versal`
- make your changes to Repo-Man and make a PR to my fork/Repo-Man branch once merged it will be added to this PR automatically
#### Changes proposed
- rename win32build directory to windows and moved it to dist directory
- added some initial fixes to  .travis.yml and  CMakeLists.txt  to accommodate these changes, this probably needs more work, **please advise**

@staticfox your stuffs for osx should be OK, but check nonetheless, my main concern is the win32build rename/and build script changes that are likely a botch at this time

### CODE REVIEW

**Comment by Stanzilla** [comment]
Why?

**Comment by staticfox** [comment]
I'm not opposed to this, though I would like myself or another dev to review and +1 this since messing with the build system can cause damage.

**Comment by un1versal** [comment]
> I'm not opposed to this, though I would like myself or another dev to review and +1 this since messing with the build system can cause damage.

Hence this is a PR should be all working 100% before merging and with feedback and seeing what breaks atm fixing it until its ready etc, without making a PR and seeing what travis/appveyor say its not simple for me.

Im sure win32build dir rename and path change alone is not properly handled as I mentioned in OP

**Comment by un1versal** [comment]
@ctrlaltca (general advice/tips) @Dessa (the windows changes) @DarthGandalf for buildsystem etc

This seems to build OK, I cant believe it was so easy can you confirm?

if you guys are OK with merging this then I can see about moving the rest of the windows stuff there if you think its wise.
If so todo list would look like....

Move from https://github.com/kvirc/KVIrc/tree/master/data
- resources_mac -> https://github.com/kvirc/KVIrc/tree/master/dist/osx
- resources_win32 -> https://github.com/kvirc/KVIrc/tree/master/dist/windows
- fix Cmakelist files and whatever else points to those paths.

If you have other suggestions or disagree with those please say.

**Comment by DarthGandalf** [comment]
> This seems to build OK

No, it's not. Until #1934 is fixed.

**Comment by un1versal** [comment]
OK this passed 64-bit the 32-bit failure is unrelated to this PR...

Merge?

**Pull request merged**
