### PR TITLE
Build also in debug mode for windows

### PR DESCRIPTION
**Pull request by DarthGandalf**
See #2191

### CODE REVIEW

**Comment by Donat76** [comment]
This would be nice. I've had a crash that has to do with adding and deleting events out of the event editor. Sometimes KVIrc crashes a few minutes later but usually not. I've been trying to reproduce it consistently. No luck so far.

**Comment by Dessa** [comment]
this is as good as it can get at this point, we need qt 5.6 for having pdb files for distribution.

**Comment by Donat76** [comment]
The x86 release build still failed for some reason? Could you remind me why qt 5.6 isn't possible at this time? Thanks.

**Comment by wodim** [comment]
That build failed because we download the spell checking dictionaries from sourceforge when we build, and the download failed for some reason.

**Comment by Donat76** [comment]
Is there any way to get this pull request into the main branch so the debug builds are built with every commit?  I would like to do what  wchristian did and use VS 2015 and track down a crash I have been getting.  If I follow his directions, it should give the exact line number in the source code where it crashes.

**Comment by wodim** [comment]
If you mean a random crash on Windows, it's probably the same...

**Comment by Donat76** [comment]
It's crashing at random times but only after adding or deleting event handlers.

**Comment by wodim** [comment]
In raw events? A crash was fixed just yesterday about that

**Comment by Donat76** [comment]
No, not the raw event editor but the regular event editor.  Could be a similar bug in the event editor module? Is the debug build going to be added to the main branch at some time instead of just being a pull request.  The one debug build is a couple commits behind the main branch already.  I download the builds directly from the Appveyor, so an up to date debug build would help.

**Pull request merged**
