### PR TITLE
Partially address #1614 - trigger texticons without control character

### PR DESCRIPTION
**Pull request by un1versal**
This Fixes `:'` and `:')` from #1614 entry without control icon

However `:P'`  and others still dont work (without a control character still and Ive no idea how to fix them.

I appreciate not many people like these, but this should work before next big release is out. this is another small step towards making this happen.

### CODE REVIEW

**Comment by DarthGandalf** [comment]
This is a completely different icon... Glasses with tongue vs eyes with teeth

**Comment by un1versal** [comment]
> This is a completely different icon... Glasses with tongue vs eyes with teeth

Dont understand whats that have to do with anything,

**Comment by DarthGandalf** [comment]
@un1versal `KviIconManager::Tongue2` is some concrete icon, right? what does it represent, glasses with tongue or eyes with teeth?

**Comment by un1versal** [comment]
capture

According to that its open eyes with tongue (could be glasses) 

If you have another suggestion that **works** for triggering it without control character, Im all ears  all my attempts to make it `8p` or `8P` failed.

**Comment by un1versal** [comment]
The issue here seems to be that any other prefix but colon has been removed intentionally so finding a key combo that still makes sense is the only workaround available and Im out of ideas atm.

**Comment by DarthGandalf** [comment]
`:B` is eyes with teeth.
If I'm typing a smiley `:B` by which I meant eyes with teeth, and suddenly it transforms into image with tongue instead of teeth, that's not very good.

**Comment by un1versal** [comment]
Right, we dont even have that image eyes with teeth or do we?

Ive literally no idea how to place this trigger, all prefix but colon has been removed on purpose according to code comments https://github.com/un1versal/KVIrc/blob/Mary-Poppins/src/kvirc/ui/KviIrcView_getTextLine.cpp#L1062-L1064

so this is broken as a result of that...

**Comment by DarthGandalf** [comment]
> Right, we dont even have that image eyes with teeth or do we?

I don't know, you're the icon guy :-P

I'm fine with having `:B`, but the image should match, and probably it shouldn't be named "tongue2" anymore, if you're changing tongue to teeth.

**Comment by un1versal** [comment]
I suppose that chnaging the icon to workaround the problem in core also would work..., yep I like that solution even if its not the right way to solve the problem, at least I can get this in and the others fixed.

**Comment by DarthGandalf** [comment]
"also"? this is what this PR does from the beginning: changes one icon to another.
I'm just asking this to be more complete (and consistent) change, not a half-way.

**Comment by un1versal** [comment]
well done the changes as discussed, and since https://github.com/kvirc/KVIrc/issues/1614 was closed with such reason merging this is now the full monty...

Ide love to drop support for these texticons but when removing the icons it will be and huge amount of work to reorganize the icons entries and fix the icons assignments in files that use numbers and not icon names...

That or do what I did for when MDI was dropped. leave a bunch of dead entries behind in code with notes and replace them with other icons.

**Comment by un1versal** [comment]
sneaking in the last splash updates... say goodbye to the splash for good say hello to release art

**Pull request merged**
