### PR TITLE
Include Debian/Ubuntu rules/scripts with KVIrc source

### PR DESCRIPTION
**Pull request by AlexanderP**

### CODE REVIEW

**Comment by DarthGandalf** [comment]
It would be good to have an additional build in Travis config which builds .deb using this...

**Comment by un1versal** [comment]
Hi AlexanderP, fantastic work.

Thanks for doing this, are you now going to be using this to build the nightlies on your ppa?

> It would be good to have an additional build in Travis config which builds .deb using this...

And upload to the FTP etc.

**Comment by DarthGandalf** [comment]
> And upload to the FTP etc.

No. How would you use it from FTP?

**Comment by un1versal** [comment]
I dont understand your question.

**Comment by DarthGandalf** [comment]
May you explain why you want to upload .deb to some FTP?

**Comment by un1versal** [comment]
You tell me ftp://ftp.kvirc.de/pub/kvirc/snapshots/ubuntu/lucid/

why do you want travis to build debs? and where will they goto?

I thought that was why PPas exist but since you talking about building debs idk.

**Comment by DarthGandalf** [comment]
No, I don't tell you.
You want .deb to be uploaded, right? So you tell me.

PPA is easier to use.

**Comment by un1versal** [comment]
> It would be good to have an additional build in Travis config which builds .deb using this...

I only said this about uploading to FTP because you said that.

I didnt quite understand what you meant then. Why is it nice for travis to build debs? for Testing only?

**Comment by wodim** [comment]
Yes, that's what continuous integration means.

**Pull request merged**
