### PR TITLE
Add Cuff-Link to server list.

### PR DESCRIPTION
**Pull request by CardinalSins**
#### Changes proposed
- Add irc.cuff-link.me/6667 and irc.cuff-link.me/6697 to the server list.

Our hostnames can be found at http://blog.cuff-link.me/chat/

User statistics can be seen at http://search.mibbit.com/networks/Cuff-Link

Additional information about us: http://irc.netsplit.de/networks/Cuff-Link/

### CODE REVIEW

**Comment by un1versal** [comment]
thx

that will save you from using http://blog.cuff-link.me/2016/05/10/kvirc-basic-setup-on-cuff-link/ in future.

**Comment by CardinalSins** [comment]
That's the idea, @un1versal. Thanks for the merge.

**Comment by un1versal** [comment]
You're welcome, :)  If you use KVIrc consider giving our nighties a trial run. You'll be pleasantly surprised.

**Comment by CardinalSins** [comment]
I'm an irssi user myself, this is for the benefit of our users.

**Pull request merged**
