### PR TITLE
Make the issue/PR templates much simpler

### PR DESCRIPTION
**Pull request by wodim**
I think the current issue/PR templates are very complex. I believe some people might feel intimidated by them, fearing the tickets will be closed or they'll be yelled at if they don't follow the template to the lettter. A bad bug report is better than no bug report at all and if there's some missing info we can always ask for it.

### CODE REVIEW

**Comment by ltc-data** [comment]
Whats worst? Making trivial pull requests that are left to fester and people feel ignored and unappreciated (like I do). 
Or making people feel unwelcome on irc?
Or accuse people on GitHub of being liars without reason?

**Comment by wodim** [comment]
Faking your own death.

**Comment by ltc-data** [comment]
hahahaha troll

I rest my case! Im out of here and will get my mates out too.

**Comment by wodim** [comment]
Merging because nobody complained.

**Pull request merged**
