### PR TITLE
Add options for kick message output

### PR DESCRIPTION
**Pull request by staticfox**
So it works fine, but I feel like it could be optimized. Not thinking straight today in light of recent events :disappointed:. Feedback?

### CODE REVIEW

**Comment by wodim** [comment]
I don't like this option.

**Comment by staticfox** [comment]
Hmm alright. Only added this due to the comments I saw when skimming through this. I personally would find it useful since I'm in > 150 channels across several networks, so when I hear my kick sound it takes me a few minutes to find out where I was kicked from, heh.

**Comment by un1versal** [comment]
+1 the current kick message is _inefficient_ to say the very least, by default the kick with reason field is populated by the username and that's it imo, not even right since you already get that info on the console. So maybe populate that message with something meaningful by default or have some sort of list. (but that client internal and not all clients have the same  system).

The situation you describe which is a perfectly acceptable scenario, I dont see what the problem here is maybe it can be achieved by catching the event and having some sort of event based reaction?

I also find wodims feedback unhelpful and vague.

**Comment by wodim** [comment]
My feedback is that we already have enough options and this is easily scriptable.

**Comment by un1versal** [comment]
Hence I suggested some event based solution.

**Comment by staticfox** [comment]
Closing in favor of better implementation.

**Comment by un1versal** [comment]
Coming to a theater near you, SOON!

**Pull request closed without merging**
