### PR TITLE
Get rid on undesired message: if its not the same on all OS's then  d…

### PR DESCRIPTION
**Pull request by un1versal**
…oesnt belong

Fix compiling on Windows also (hopefully)

### CODE REVIEW

**Comment by un1versal** [comment]
I wonder if https://github.com/kvirc/KVIrc/blob/0d4df593543eb3ae1997ceec47028da851f7c9b9/src/kvirc/kernel/KviIpcSentinel.cpp#L39-L47 is looking for the window title to be `kvirc4_ipc_sentinel`

**Comment by ctrlaltca** [comment]
Exactly. This commit https://github.com/un1versal/KVIrc/commit/f41c1f2868ee7d318b29e4c076db45a8b0346b3d#diff-bb6b2b0631283944011aa0ef4ca449d8L220 actually broke the IPC sentinel.
IPC stands for inter-process communication. When you run KVIrc, it will first check if a KVIrc instance is already running and "pass the command" to that instance instead of opening a new one.
I suppose this is related to #1885

**Comment by ctrlaltca** [comment]
Also, that string would be better placed in a constant so that it's easy to detect that it should not be changed.

**Comment by Dessa** [comment]
so i suppose that specific string isn't user facing at all and should be put back the way it was before?

**Comment by ctrlaltca** [comment]
I've opened #1892, let's wait for appveyor to finish the build and test its output.

**Comment by un1versal** [comment]
#1885 was already broken before https://github.com/un1versal/KVIrc/commit/f41c1f2868ee7d318b29e4c076db45a8b0346b3d#diff-bb6b2b0631283944011aa0ef4ca449d8L220

thx in any case https://github.com/kvirc/KVIrc/pull/1891 at least fixed compiling

**Pull request merged**
