### PR TITLE
AppVeyor: Use latest Qt

### PR DESCRIPTION
**Pull request by craftwar**
We don't need change Qt version any more. It will use latest release on AppVeyor.

### CODE REVIEW

**Comment by DarthGandalf** [comment]
I have mixed feelings about this.
One one hand, it requires less changes from us, and keeps the version up to date.
On the other hand, the version changes randomly underneath, so e.g. when KVIrc 5 is going to be released, Appveyor changes the latest Qt version, and KVIrc is released with unknown bugs, because it was never tested on that version of Qt (on windows).

**Comment by craftwar** [comment]
For stable, keep it on 5.9 TLS is good choice.
How about adding another matrix? Use latest for building test only, fix any issue introduced by newer Qt.
con: make build time longer

**Comment by Stanzilla** [comment]
I vote nay because of exactly what DarthGandalf said. Another matrix would be fine but as you already said, longer build times and we are already super slow there.

**Comment by craftwar** [comment]
Close, don't change Qt til next TLS 5.12.

**Pull request closed without merging**
