### PR TITLE
Substitute tabs with spaces before they are painted.

### PR DESCRIPTION
**Pull request by wodim**
#1855

There's like one thousand places in the code where you could put this. Every place has its complications. Whatever you do you feel guilty knowing you're ruining the performance.

### CODE REVIEW

**Comment by IceN9ne** [comment]
Consider doing this in a different place where the lines are being added so that it only needs to happen once per line and not on every paint.  Maybe `KviIrcView::appendLine` or before it gets here.

I can't think of a reason tabs would need to be preserved unless it somehow allows the tabs to be preserved when you highlight-copy.

Also, we have a configuration for how many spaces a tab is replaced with for input, maybe do this for output as well?  Use same setting or new setting?

**Comment by wodim** [comment]
What about this steaming pile of shit?

I really don't know what to do. I can't do the replacement later because I'd have to recalculate all the places where the length of the string and the chunks and whatever are stored. I can't do the replacement before (when it still is a kvi_wchar_t) because everything is marked const until the origin, and then I'd have to do the replacement in several places.

**Comment by the-j0k3r** [comment]
How about adding a default event script to [b]OnTextInput[/b] that does a string replacement of tabs and accounts for **option uintSpacesToExpandTabulationInput** userset value

Or did I misunderstand the problem?

**Comment by IceN9ne** [comment]
`OnTextInput` is when the user types something in. This PR is for when you receive messages from other users that have tabs in them and are painted to the `IrcView` window causing odd display issues.

**Comment by the-j0k3r** [comment]
There are OnChannelMessage and OnQueryMessage also to handle incoming if that's the problem. In either case, Im not volunteering :)

**Pull request closed without merging**
