### PR TITLE
cache the Strawberry dir

### PR DESCRIPTION
**Pull request by Stanzilla**
I actually wanted to cache the Chocolatey dir first but the appveyor config is a bit weird, in the logs it looked like it should use some sort of cached/already existing strawberry installation but that is never true on appveyor so it always downloads and installs and then patches it, this caching should make this faster.

### CODE REVIEW

**Comment by ltc-data** [comment]
this was removed in https://github.com/kvirc/KVIrc/commit/ae97a8ffad491124f93be0d38798cbbc8a4af6ce

**Review by Dessa — COMMENTED** [review]
if you are touching these anyway, you could also update to 2017.08.24

**Review by Dessa — COMMENTED** [review]
IIRC the cache isn't even re-used for PRs, but i could be wrong here

**Comment by Stanzilla** [comment]
Yeah certainly looks like it. How to best test if it does not then? New branch?

**Comment by Stanzilla** [comment]
Yup, still too large 

```
Cache 'c:\Strawberry' - Uploading (151,131,111 bytes)...100%
Error uploading cache entry to the cache storage: The maximum cache size of 1,000 MB will be exceeded.
```

**Comment by Stanzilla** [comment]
@Dessa will experiment with https://github.com/Microsoft/vcpkg next when he has time.

**Pull request closed without merging**
