### PR TITLE
Drop support of Qt4 from CMakeLists

### PR DESCRIPTION
**Pull request by DarthGandalf**
All C++ #ifdefs are still there... See #1650

Also switch Travis to Qt5

### CODE REVIEW

**Comment by wodim** [comment]
Travis on OS X fails.

**Comment by DarthGandalf** [comment]
@wodim Not anymore.
Though before merging this I'd prefer everyone (e.g. @ctrlaltca) to object if they want.

**Comment by un1versal** [comment]
from #1850 
capture

I guess the INSTALL docs will need to reflect this also. 

my +1 for this here for what is worth.

**Comment by ctrlaltca** [comment]
I have no objections :+1:

**Pull request merged**
