### PR TITLE
remove russian website and mailing list links from help menu

### PR DESCRIPTION
**Pull request by Stanzilla**

### CODE REVIEW

**Comment by DarthGandalf** [comment]
kvirc.ru is still up...

**Comment by swarfega** [comment]
Could we use the template from .ru on .net?

**Comment by DarthGandalf** [comment]
It's MediaWiki

**Comment by swarfega** [comment]
It looks nicer than the .net website imo.

**Comment by Stanzilla** [comment]
.ru is still up but not updated and "under our control" or is it your site, @DarthGandalf I don't even know

**Comment by DarthGandalf** [comment]
No, it's by another Alexey... I'll contact him.

**Comment by Stanzilla** [comment]
Thanks, I think it's risky to point people to a website we don't have control over. Could change any day and then scam people

**Comment by auzhva** [comment]
Hi everyone:)

I’m that Alexey, that you are looking for:) That created kvirc.ru site and actually Russian community community quite a while ago.

Despite not being updated too often, it still has some traffic. And downloads from there.

So I don’t think shutdowns is a great way to go. 

It would be absolutely great if someone from here wants to contribute. That person doesn’t need permission. It’s wiki. Just do!

If someone trusted wants to have admin permission to make it better - let’s do so as well

**Comment by auzhva** [comment]
Btw, this site might be not updated, but it will never ever scam people;)

**Pull request merged**
