### PR TITLE
Fix fixup_bundle() on osx + qt >= 5.5

### PR DESCRIPTION
**Pull request by ctrlaltca**

### CODE REVIEW

**Comment by DarthGandalf** [comment]
I think, need to add one more build to travis, currently it uses only qt4 on osx.

**Comment by ctrlaltca** [comment]
> I think, need to add one more build to travis, currently it uses only qt4 on osx.

You are right; also, as an user, i see no reason to choose qt4 over qt5 on osx.

**Comment by staticfox** [comment]
> You are right; also, as an user, i see no reason to choose qt4 over qt5 on osx.

Perhaps we can use this as an excuse to start slowly migrating away from qt4?

**Comment by DarthGandalf** [comment]
@ctrlaltca `brew install qt` vs `brew install qt5`?

**Comment by ctrlaltca** [comment]
@DarthGandalf exactly; also:
- cmake => 2.8.12 is needed, but homebrew already provides 3.x, so no problem;
- we need to pass -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.whatever/ to cmake

Example: https://github.com/Cockatrice/Cockatrice/blob/master/travis-compile.sh

**Comment by DarthGandalf** [comment]
I prefer `brew --prefix qt5`, it looks a bit nicer than `echo`

Also I see, you do the same for linux, but `source /opt/qt55/bin/qt55-env.sh` should be enough with beineri's ppa

**Comment by ctrlaltca** [comment]
Yep, `source /opt/qt55/bin/qt55-env.sh` should suffice
I had to add the LD_LIBRARY_PATH thing to have cpack determine the binary dependencies for the debian package.

**Comment by un1versal** [comment]
is this good to go in?

**Pull request merged**
