### PR TITLE
NOT for merging, this is just for personal curiosity.

### PR DESCRIPTION
**Pull request by un1versal**
Just want to see what happens.

### CODE REVIEW

**Comment by ctrlaltca** [comment]
:bomb: :boom:

**Comment by un1versal** [comment]
> :bomb: :boom:

very likely but noone will get hurt. :laughing:

**Comment by un1versal** [comment]
Not bad.... one error fixed.

```
c:\cygwin\bin\touch : /usr/bin/touch: cannot touch '/cygdrive/c/Strawberry/kvirc_workaround': No such file or directory
At line:7 char:5
+     c:\cygwin\bin\touch /cygdrive/c/Strawberry/kvirc_workaround
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (/usr/bin/touch:...le or directory:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Command executed with exception: /usr/bin/touch: cannot touch '/cygdrive/c/Strawberry/kvirc_workaround': No such file or directory
```

isnt there anymore.

**Comment by un1versal** [comment]
it was fun while it lasted :grin:

**Pull request closed without merging**
