### PR TITLE
Add warning for invalid options_group in options.dialog

### LINKED ISSUE #1754: running options.dialog <something> opens a Preferences dialog with no settings.
The docs say 

```
Shows the KVIrc options dialog for the specified options group. If the [-t] switch is used, the dialog is opened as toplevel window, otherwise it is opened as part of the current frame window.
Valid values for [options_group] are "general" and "theme". If [options_group] is omitted, the option group "general" is assumed. This command is exported by the "options" module.
```

But if you run  `options.dialog <something>` where `<something>` is not **general** or **theme**,  the unexpected happens.

capture

*_also_ `options.dialog -t general` does the same and omitting `-t`

```
KVIrc 4.3.2 'Aria'

Runtime Info:
System Name: Linux 3.13.0-68-generic
System Version: #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015
Architecture: x86_64
Qt Version: 5.2.1

Build Info:
Build Date: 2015-12-05 13:58:43 UTC
Sources Date: 20151205
Revision Number: git-5745-gd82a8a8
System Name: Linux-3.13.0-68-generic
CPU Name: x86_64
Build Command: /usr/bin/cmake
Build Flags: 
   MANDIR=man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler Name: /usr/bin/c++
Compiler Flags: N/A
Qt Version: 5.2.1
```

### PR DESCRIPTION
**Pull request by ghost**
Issue #1754 

Instead of opening an empty options.dialog when something other than "general" or "theme" is typed, this will instead return a warning and stop the command.

### CODE REVIEW

**Comment by un1versal** [comment]
:+1: sounds fair enough, thank you

**Comment by un1versal** [comment]
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by ghost** [comment]
@un1versal 

I don't do that on purpose, as I'm not an official KVIrc anything, so I don't feel it's my place to say whether or not my suggested fix does or doesn't fully close an issue.

Also, I recommend https://github.com/blog/1506-closing-issues-via-pull-requests as a better alternative to adding extra length and confusion to a commit message, which in my opinion should be as clear and concise as possible.

**Comment by un1versal** [comment]
However you are most comfortable.

Its no big deal, From my part the view is use the tools at your disposal to make everyone's jobs easier. A pr that adds magic words and is merged and closes the related issue, is A OK and desired imo. 

In the offchance, anyone disagrees at any later time or the fix would for some reason not actually fix the issue we can always reopen ticket.

But like I said, however you're most comfortable.

Anyway, thanks, youre fixing issues and that is officially welcome, your position being official or not can change at any time ;)

**Pull request merged**
