### PR TITLE
fix typo in ignoreEnagled -> ignoreEnabled

### PR DESCRIPTION
**Pull request by un1versal**

### CODE REVIEW

**Comment by Stanzilla** [comment]
Is that actually the reason why ignoring is so broken right now? Because that would be hilarious..

**Comment by staticfox** [comment]
Extremely unlikely

**Comment by un1versal** [comment]
No idea actually if this is the reason. Who knows.

what you think staticfox? seems OK to merge no?

**Comment by un1versal** [comment]
Oopsy! Seems like it didnt like what I did

```
home/travis/build/kvirc/KVIrc/src/kvilib/ext/KviRegisteredUserDataBase.cpp: In member function ‘void KviRegisteredUserDataBase::save(const QString&)’:

/home/travis/build/kvirc/KVIrc/src/kvilib/ext/KviRegisteredUserDataBase.cpp:526:48: error: ‘class KviRegisteredUser’ has no member named ‘ignoreEnabled’

   cfg.writeEntry("IgnoreEnabled",it.current()->ignoreEnabled());

                                                ^

make[2]: *** [src/kvilib/CMakeFiles/kvilib.dir/ext/KviRegisteredUserDataBase.cpp.o] Error 1

make[1]: *** [src/kvilib/CMakeFiles/kvilib.dir/all] Error 2

make: *** [all] Error 2
```

**Comment by staticfox** [comment]
yeah you didnt even change the actual function declaration

**Comment by staticfox** [comment]
`src/kvilib/ext/KviRegisteredUser.h`

**Comment by un1versal** [comment]
good to go I think...

**Pull request merged**
