### PR TITLE
Update and add new info to Readme.md

### PR DESCRIPTION
**Pull request by un1versal**
This is how it will look https://github.com/uNiversaI/KVIrc/blob/Mary-had-a-little-lamb/README.md

### CODE REVIEW

**Comment by DarthGandalf** [comment]
What is "x32"?
How such tooltips can help with anything? there is already a text of the
link.

2015-09-08 11:46 GMT+01:00 uNiversaI notifications@github.com:

**Comment by un1versal** [comment]
> What is "x32"? How such tooltips can help with anything? there is already a text of the link.

That' a brain fart, probably due to Win32 install readme nonsense, fixed.

Tootips for the nerds, I can remove it if its such eye sore :smile: 

> Nightly sounds better than master and most people understand that

Sure I dont mind but that gives impression its built nightly and that's not really accurate.

**Comment by wodim** [comment]
Please remove useless tooltips also.

**Comment by un1versal** [comment]
All done.

**Comment by wodim** [comment]
:thumbsup:, but I'll wait for someone else

**Pull request merged**
