### PR TITLE
Remove deprecated and unused QMatrix references

### PR DESCRIPTION
**Pull request by ghost**
The `QMatrix` class has been deprecated in Qt5.  I also couldn't find anywhere where `m_pMatrix` (which isn't even declared as a pointer) used in the current code.

### CODE REVIEW

**Comment by un1versal** [comment]
Im not familiar with these things, but Qt4 is still supported, what happens with this in those instances?

Somewhat related #1650

**Comment by DarthGandalf** [comment]
If this compiles, should be fine.
Windows failed build doesn't seem related to this.

**Comment by ghost** [comment]
@un1versal It's just a straight deletion of 2 unused lines, so even if we still support Qt4, it won't change anything.

**Comment by un1versal** [comment]
:+1: for cleaning up

**Comment by un1versal** [comment]
failure is related to https://github.com/kvirc/KVIrc/issues/1769 this has been blessed so its in. thx.

**Pull request merged**
