### PR TITLE
Add SSL urls (ircs/ircs6) in server options dialog.

### PR DESCRIPTION
**Pull request by ghost**
Adds dynamic display of ircs:// and ircs6:// when "Use SSL" checkbox is toggled.

Fixes typo in irc6s warning.

### CODE REVIEW

**Comment by wodim** [comment]
Does this work at all?

**Comment by ghost** [comment]
Why wouldn't it?  It worked previously for irc:// and irc6:// .  I just extended it for SSL and had it actually display the "s".

**Comment by wodim** [comment]
Eh, nothing.

**Comment by un1versal** [comment]
/me does Frankenstein voice and shouts —"It liiveess!"

**Comment by un1versal** [comment]
there only one ommission I can tell here., while on terminal type `kvirc --help`

one of the outpust is as follows:

```
  [ircurl]     : URL in the following form:
                 irc[6]://<server>[:<port>][/<channel>[?<pass>]]
```

should it be:

`irc[s][6]://`

**Comment by ghost** [comment]
The only problem with that change is that the command line option [ircurl] doesn't support enabling ssl with ircs:// designation. (Not that I could get to work anyways)

That would require separate commit.  This was just for a display fix.

**Pull request merged**
